---
- name: Generate a new secret for an Azure Application registration and update Azure Key Vault
  hosts: localhost
  gather_facts: no
  vars_files:
    - azure_credentials.yml  # Reference the credentials file
  tasks:
    - name: Authenticate with Azure
      azure.azcollection.azure_rm_auth:
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
        subscription_id: "{{ azure_subscription_id }}"
