---
- name: Generate a new secret for an Azure Application registration and update Azure Key Vault
  hosts: localhost
  gather_facts: no
  vars:
    azure_subscription_id: "your_subscription_id"
    azure_client_id: "your_client_id"
    azure_secret: "your_secret"
    azure_tenant: "your_tenant_id"
    application_id: "your_application_id"
    secret_description: "NewSecret"
    secret_duration: "P1Y"  # Duration in ISO 8601 format (e.g., P1Y for 1 year)
    keyvault_name: "your_keyvault_name"
    keyvault_secret_name: "your_keyvault_secret_name"
 
  tasks:
    - name: Authenticate with Azure
      azure.azcollection.azure_rm_auth:
        client_id: "{{ azure_client_id }}"
        secret: "{{ azure_secret }}"
        tenant: "{{ azure_tenant }}"
        subscription_id: "{{ azure_subscription_id }}"
 
    - name: Generate a new secret for the Azure Application
      azure.azcollection.azure_rm_adapplication:
        application_id: "{{ application_id }}"
        password_credentials:
          - display_name: "{{ secret_description }}"
            end_date: "{{ (ansible_date_time.iso8601 | to_datetime) + secret_duration | to_datetime | string }}"
      register: new_secret
 
    - name: Display the new secret value
      debug:
        msg: "New secret value: {{ new_secret.password_credentials[0].secret_text }}"
 
    - name: Update the secret value in Azure Key Vault
      azure.azcollection.azure_rm_keyvaultsecret:
        vault_uri: "https://{{ keyvault_name }}.vault.azure.net/"
        secret_name: "{{ keyvault_secret_name }}"
        secret_value: "{{ new_secret.password_credentials[0].secret_text }}"
